### ISSUE TITLE
Update of PouchDB ?

### ISSUE THREAD

**Issue by ronycohen** [ermouth/cloudwall#17]
Hello, the CloudWall Version of PouchDB is the V3.3.1
PouchDB is currently working at the V5.3.2

Is it possible tu use the last version ?

**Comment by ermouth** [comment]
Hi.

Actually both CW 1.9 and 2.0 use patched Pouch 3.3.1. All my attempts to use version 3.6+, 4.x and 5.x failed sooner or later. 

Main issue is replication a) of DBs with a lot of large docs, b) simultaneous replication of several DBs. Those issues are fixed in the patched version.

Also patched version never use Blobs of IDB, that degrades performance, however guarantees normal operation (read – no data loss) on old Chromes (44-) and after old Chrome‘s update to newer version.

Since careful testing of new PouchDB versions in real scenarios takes _enormous_ amount of time, I‘ve decided to plan Pouch upgrade only after I see no common replication issues at PouchDB tracker at least for 3 month.

Upgrade will need minor CW code refactoring since I use callbacks in several places, that are obsolete. Latest versions of PouchDB use promises.

**Comment by ronycohen** [comment]
Hello, 
Thank you for the explanation !
CouchDB 2.0 improved consequently the files management.
I think it's a game changer, you should look at it.

**Comment by ermouth** [comment]
> CouchDB 2.0 improved consequently the files management
> you should look at it.

Thank you, but at least this particular bug https://twitter.com/ermouth/status/722402831253245952 makes Fauxton useless for me.

**Comment by ronycohen** [comment]
ah Yes you are definitely right :)
