### ISSUE TITLE
Localhost CORS, why must ddoc.me be set up in your local-to-local sync 

### ISSUE THREAD

**Issue by johs** [ermouth/cloudwall#5]
Why must ddoc.me be accepted in a CORS setup in your local instance of CoucnDB where the sync goes from your local storage to the local Couch?

**Comment by ermouth** [comment]
It must not. You see this text when start from Couch? It must be hidden in this case.

**Comment by johs** [comment]
[Error] Failed to load resource: the server responded with a status of 405 (Method Not Allowed) (app, line 0)
Seems to be a Safari problem. Chrome worked well. Here's the screenshot from Safari.
<img width="814" alt="screen shot 2015-08-03 at 04 16 51" src="https://cloud.githubusercontent.com/assets/48370/9029631/1fbc6444-3997-11e5-82c0-de6ff0fed3ac.png">

**Comment by ermouth** [comment]
Ah, understood, it‘s not about standalone version. 

Better avoid 127.0.0.1 – it cause issues here or there in different browsers. It‘s not DdocLab fault – it‘s about localhost security policy incosistency across browsers. 

Allowing free access to 127.0.0.1 in general is a threat. Since localhost is invisible from outside, you give an outside resource rights to access your local private data, that is risk.

**Comment by johs** [comment]
It still works in Chrome, though. So what should I do, adding "127.0.0.1    couch" to /etc/hosts to use http://couch:5984/ would not work.
It even did not let Ddoc Lab start (even though I reached the db and Ddoc Lab's design document)

**Comment by ermouth** [comment]
Use your local IP. Or try to write /hosts as `127.0.0.1 couch.local` – possibly it help.

**Comment by johs** [comment]
http://127.0.0.1:5984/sayprojects/ work in Chrome
after adding to etc/hosts "127.0.0.1 couch.local "

http://couch.local:5984/ddoctest/_design/ddoclab18/index.html#1438442892054hj0dey5
(my local Ddoc Lab) would "Failed to start" (need to run from 127.0.0.1 to start)

**Comment by ermouth** [comment]
Tested both in Safari and Chrome with 127.0.0.1 and empty /etc/hosts – everythng is fine when I start from Couch as a couchapp. 

Although when I try to sync with 127.0.0.1 from ddoc.me standalone, see errors in both browsers.

It‘s different from your results – that proves my point about issues here and there with 127.0.0.1 in different browsers. 

Since I can‘t reproduce all possible localhost configurations and test them, better avoid it. Not sure everything will work fine even if it seems to be working fine now.

**Comment by johs** [comment]
I still have problems w Safari, and it gives med "Failed to start" without any error in the console, but I think this issue needs to be addressed in separate detailed issues.
